import{a as f,i,S as b}from"./assets/vendor-08b0e0f9.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const L=document.querySelector(".form"),l=document.querySelector(".load_more");f.defaults.baseURL="https://pixabay.com/api";let u=1,q=40,c="";async function d(r){const a="41833958-d4e1402628473c9a9cbd6bb32",o=new URLSearchParams({key:a,q:r.toLowerCase(),per_page:q,page:u,image_type:"photo",orientation:"horizontal",safesearch:!0}),s=await f.get(`/?${o}`);if(s.status!==200)throw new Error("No images found. Please try again with a different search query.");return s.data}function m(r,a=!1){const o=document.querySelector(".gallery");if(a||(o.innerHTML=""),r.hits.length===0){i.error({message:"No images found. Please try again with a different search query."});return}const s=r.hits.map(({webformatURL:t,largeImageURL:n,tags:y,likes:g,views:p,comments:h,downloads:w})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${n}">
                <img class="gallery-image" src="${t}" alt="${y}" />
            </a>
            <div class="image-details">
                <p>Likes </br> ${g}</p>
                <p>Views </br>  ${p}</p>
                <p>Comments </br>  ${h}</p>
                <p>Downloads </br>  ${w}</p>
            </div>
        </li>`).join("");o.innerHTML+=s,new b(".gallery a").refresh(),l.style.display="block"}async function P(r){r.preventDefault(),l.style.display="none";const a=r.currentTarget,o=a.elements.query.value;if(c=o,!o){i.warning({message:"Please enter a search query."});return}try{const s=await d(c);m(s),u=1}catch(s){i.error({message:s.message})}finally{a.reset()}}async function E(r){try{return await d(r)}catch{throw new Error("Error load new images.")}}async function S(){try{const r=await E(c);u+=1,m(r,!0)}catch{throw new Error("Error load new images.")}}async function $(){if(!c){i.warning({message:"Please enter a search query."});return}try{await S()}finally{}}L.addEventListener("submit",P);l.addEventListener("click",$);
//# sourceMappingURL=commonHelpers.js.map
