import{S as L,a as y,i as n}from"./assets/vendor-08b0e0f9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const q=document.querySelector(".form"),l=document.querySelector(".load_more"),P=new L(".gallery a"),d=document.querySelector(".loader");y.defaults.baseURL="https://pixabay.com/api";let c=1,g=100,u="";async function m(e){const t="41833958-d4e1402628473c9a9cbd6bb32",a=new URLSearchParams({key:t,q:e.toLowerCase(),per_page:g,page:c,image_type:"photo",orientation:"horizontal",safesearch:!0});d.style.display="block";const s=await y.get(`/?${a}`);if(s.status!==200)throw new Error("No images found. Please try again with a different search query.");return s.data}function f(e,t=!1){const a=document.querySelector(".gallery");if(t||(a.innerHTML=""),e.hits.length===0){n.error({message:"No images found. Please try again with a different search query."});return}const s=e.hits.map(({webformatURL:r,largeImageURL:o,tags:i,likes:h,views:p,comments:w,downloads:b})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${o}">
                <img class="gallery-image" src="${r}" alt="${i}" />
            </a>
            <div class="image-details">
                <p>Likes </br> ${h}</p>
                <p>Views </br>  ${p}</p>
                <p>Comments </br>  ${w}</p>
                <p>Downloads </br>  ${b}</p>
            </div>
        </li>`).join("");a.innerHTML+=s,P.refresh(),t||(l.style.display="block"),d.style.display="none",l.style.display="block"}async function E(e){e.preventDefault(),l.style.display="none";const t=e.currentTarget,a=t.elements.query.value;if(u=a,!a){n.warning({message:"Please enter a search query."});return}c=1;try{const s=await m(u);f(s)}catch(s){n.error({message:s.message})}finally{t.reset()}}async function M(e){try{return await m(e)}catch{n.error({message:"Error load new images."})}}async function S(){try{const e=await M(u),t=Math.ceil(e.totalHits/g);if(c>t){n.error({message:"We're sorry, but you've reached the end of search results."}),l.style.display="none";return}c++,f(e,!0);const a=$();window.scrollBy({top:a*2,behavior:"smooth"})}catch{n.error({message:"Error load new images."})}d.style.display="none"}async function v(){if(d.style.display="block",!u){n.warning({message:"Please enter a search query."});return}try{await S()}catch(e){throw console.error('Error during handling "Load More":',e),new Error("Error during handling 'Load More'.")}}q.addEventListener("submit",E);l.addEventListener("click",v);function $(){const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0}
//# sourceMappingURL=commonHelpers.js.map
